import type { ProjectSnapshot, ProjectSnapshotChapter, ProjectSnapshotScene } from '@/auth'
import type { LandingChapter, LandingScene } from '@/components/landing/types'

const getString = (value: unknown, fallback = '') => (typeof value === 'string' && value.trim() ? value : fallback)
const getNumber = (value: unknown, fallback = 0) => (typeof value === 'number' && Number.isFinite(value) ? value : fallback)

const chapterId = (chapter: ProjectSnapshotChapter, index: number) => getString(chapter.chapter_id ?? chapter.ChapterID ?? chapter.id ?? chapter.ID, `chapter-${index + 1}`)
const sceneId = (scene: ProjectSnapshotScene, index: number) => getString(scene.scene_id ?? scene.SceneID ?? scene.id ?? scene.ID, `scene-${index + 1}`)

export const snapshotToLandingChapters = (snapshot: ProjectSnapshot): LandingChapter[] => {
  const chapters = snapshot.chapters ?? snapshot.Chapters ?? []
  const flatScenes = snapshot.scenes ?? snapshot.Scenes ?? []

  return chapters.map((chapter, chapterIndex) => {
    const id = chapterId(chapter, chapterIndex)
    const index = getNumber(chapter.chapter_index ?? chapter.ChapterIndex, chapterIndex + 1)
    const scenes = flatScenes
      .filter((scene) => getString(scene.chapter_id ?? scene.ChapterID) === id)
      .sort((a, b) => getNumber(a.scene_index ?? a.SceneIndex) - getNumber(b.scene_index ?? b.SceneIndex))
      .map<LandingScene>((scene, sceneIndex) => ({
        id: sceneId(scene, sceneIndex),
        num: String(getNumber(scene.scene_index ?? scene.SceneIndex, sceneIndex + 1)).padStart(2, '0'),
        title: getString(scene.title ?? scene.Title, `Scene ${sceneIndex + 1}`),
        intent: getString(scene.summary ?? scene.Summary ?? scene.status ?? scene.Status, 'Generated Scene'),
        comment: getString(scene.design_reason_y_a_m_l ?? scene.DesignReasonYAML ?? scene.summary ?? scene.Summary, 'Generated by backend.'),
        yaml: getString(scene.editable_y_a_m_l ?? scene.EditableYAML ?? scene.generated_y_a_m_l ?? scene.GeneratedYAML),
      }))

    return {
      id,
      num: `CH. ${String(index).padStart(2, '0')}`,
      title: getString(chapter.title ?? chapter.Title, `Chapter ${index}`),
      open: chapterIndex === 0,
      scenes,
    }
  })
}
